apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  name: redhat-gpte-gitea
  namespace: openshift-marketplace
spec:
  sourceType: grpc
  image: quay.io/gpte-devops-automation/gitea-catalog:latest
  displayName: Red Hat GPTE (Gitea)
  publisher: Red Hat GPTE
